apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-02-02T12:09:07Z"
  labels:
    run: hello-world
  name: hello-world
  namespace: default
  resourceVersion: "3863"
  uid: 968c69a8-04b3-462e-bf42-63d884d9e6fc
spec:
  containers:
  - image: codely-docker:latest
    imagePullPolicy: Always
    name: hello-world
    ports:
    - containerPort: 80
      protocol: TCP
    resources: 
      limits:
        cpu: 50m
        memory: 23Mi
      requests:
        cpu: 50m
        memory: 23Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8q24t
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-8q24t
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  phase: Pending
  qosClass: BestEffort